baseURL = "http://all-of-time-and-space.de/"
languageCode = "en-us"
title = "All of Time and Space"
theme = "travel-blog"
publishDir = "docs"

[params]
  description = "Lilo and Mike's Travel Blog"
  twitter = ""
  insta = ""

[markup.goldmark.renderer]
  unsafe= true
