options:
  merge-default-rules: false
  formatter: html
  output-file: 'sass-lint.html'
# File Options
files:
  include: 'src/scss/**/*.scss'
  ignore: 'src/scss/override/*.scss'
# Rule Configuration
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  mixins-before-declarations: 2
  no-color-hex: 1
  no-warn: 1
  no-debug: 1
  no-important: 2
  indentation:
    - 2
    - size: 2
  property-sort-order:
    - 1
    - order: 'concentric'
